### Configure database migration script
apiVersion: v1
kind: ConfigMap
metadata:
  name: wipp-migrate-database-v3-1-0
data:
  wipp-migrate-database-v3-1-0.js: |
    db.genericFile.dropIndex("collection_filename");
---
### Run a job to perform database migration from WIPP beta to WIPP 3.0.0
apiVersion: batch/v1
kind: Job
metadata:
  name: wipp-migrate-database-v3-1-0
spec:
  template:
    spec:
      containers:
      - name: wipp-migrate-database-v3-1-0
        image: mongo:3.6
        command: [ "mongo", "wipp-mongo:27017/wipp", "/scripts/wipp-migrate-database-v3-1-0.js" ]
        volumeMounts:
          - name: wipp-database-migration-scripts
            mountPath: /scripts
      volumes:
      - name: wipp-database-migration-scripts
        configMap:
          name: wipp-migrate-database-v3-1-0
          items:
          - key: wipp-migrate-database-v3-1-0.js
            path: wipp-migrate-database-v3-1-0.js
      restartPolicy: Never
  backoffLimit: 4
---
