apiVersion: v1
kind: ServiceAccount
metadata:
  name: wipp-backend-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wipp-backend-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "patch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflows"]
    verbs: ["delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wipp-backend-rb
subjects:
  - kind: ServiceAccount
    name: wipp-backend-sa
roleRef:
  kind: Role
  name: wipp-backend-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wipp-backend
spec:
  selector:
    matchLabels:
      app: wipp-backend
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: wipp-backend
    spec:
      serviceAccountName: wipp-backend-sa
      containers:
      - image: WIPP_BACKEND_IMAGE
        name: wipp-backend
        args: ["mongodb", "27017", "wippdata-pvc"]
        env:
            - name: KEYCLOAK_AUTH_URL
              value: KEYCLOAK_AUTH_URL_VALUE
            - name: KEYCLOAK_SSL_REQUIRED
              value: KEYCLOAK_SSL_REQUIRED_VALUE
            - name: KEYCLOAK_DISABLE_TRUST_MANAGER
              value: KEYCLOAK_DISABLE_TRUST_MANAGER_VALUE
            - name: ELASTIC_APM_SERVER_URLS
              value: ELASTIC_APM_SERVER_URLS_VALUE
            - name: ELASTIC_APM_SERVICE_NAME
              value: wipp-backend
            - name: ELASTIC_APM_APPLICATION_PACKAGES
              value: gov.nist.itl.ssd.wipp.backend
        volumeMounts:
        - mountPath: /data/WIPP-plugins
          name: data
        ports:
        - containerPort: 8080
        resources: {}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: wippdata-pvc
      restartPolicy: Always
status: {}
