apiVersion: v1
kind: Service
metadata:
  labels:
    service: wipp-frontend
  name: wipp-frontend
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
  selector:
    app: wipp-frontend