apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: wipp-frontend
  name: wipp-frontend
spec:
  selector:
    matchLabels:
      app: wipp-frontend
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wipp-frontend
    spec:
      containers:
      - image: WIPP_FRONTEND_IMAGE
        name: wipp-frontend
        args: ["wipp-backend", "8080"]
        env:
        - name: ARGOUIBASE_URL
          value: ARGOUIBASE_URL_VALUE
        - name: KEYCLOAK_URL
          value: KEYCLOAK_URL_VALUE
        - name: TENSORBOARD_URL
          value: TENSORBOARD_URL_VALUE
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        resources: {}
      restartPolicy: Always
status: {}
